### ISSUE TITLE
github CI implementation produces toctree error

### ISSUE THREAD

**Issue by jvmead** [hsf-training/analysis-essentials#25]
Using github's inbuilt CI on [patch-1](https://github.com/jvmead/analysis-essentials/tree/patch-1) branch to avoid timeout issues with travis for hyperparamter lesson, switching to .github/workflows/ci.yaml but now have issues with the [following](https://github.com/jvmead/analysis-essentials/runs/1449698500):
```
Warning, treated as error:
/home/runner/work/analysis-essentials/analysis-essentials/build/doctrees/nbsphinx/advanced-python/1Basics.ipynb: document isn't included in any toctree
```

**Comment by jonas-eschle** [comment]
This means that Basic is not included in any toctree and needs to be added. But I believe this was fixed as the ci passes now. Maybe close this?

**Comment by jvmead** [comment]
apologies I just found these emails in my junk, will close now, cheers for the update!
