### ISSUE TITLE
Repeating python statements in 10Basics module

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/analysis-essentials#39]
In the [file](https://github.com/hsf-training/analysis-essentials/blob/master/advanced-python/10Basics.ipynb), it seems that there are extra ```python {'a': 'b'}.get``` statements

**Comment by jonas-eschle** [comment]
Hi @amanmdesai , thanks a lot for bringing up the issue. I don't quite find it though.
Also, are you aware how to make pull requests? You can fork the repository, clone it, fix it, push it to your clone and them make a PR. Do you know these steps or are they new for you?
