### ISSUE TITLE
Introducing the Shell - Prerequisites

### ISSUE THREAD

**Issue by jvmead** [hsf-training/analysis-essentials#4]
```unzip:  cannot find or open data-shell.zip, data-shell.zip.zip or data-shell.zip.ZIP.```
 returned when running the command in lesson page https://hsf-training.github.io/analysis-essentials/shell/
I've had a quick read ahead and back and I don't think I'm missing anything that would make a difference.

**Comment by chrisburr** [comment]
Does this new version of that line work for you?

https://github.com/hsf-training/analysis-essentials/pull/5/files#diff-4d85b8ebc9d8b42e02b00508fbf09462R14

**Comment by jvmead** [comment]
spot on :)

**Comment by chrisburr** [comment]
Thanks for reporting it! 😄
