### ISSUE TITLE
Error while building web pages

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/analysis-essentials#41]
There seems to be some error in building webpage. 

The error is: 
Notebook error:
CellExecutionError in advanced-python/45DemoReweighting.ipynb

The full error message is here: [LINK](https://github.com/hsf-training/analysis-essentials/runs/7850689023?check_suite_focus=true)

**Comment by jonas-eschle** [comment]
Yes, and it has to do with downloading the data with uproot, somehow this is not stable. Are you familiar with uproot?

**Comment by amanmdesai** [comment]
Hi,

Yes I am familiar with uproot.

I ran the 45DemoReweighting.ipynb notebook in Google Colab and it runs successfully without error.

The google colab uses Python 3.7 and uproot version: 4.3.4

Maybe it's an error with the framework?

In my fork I changed the environment.yml file slightly (updating the uproot version) and the notebook builds successfully. I will open a PR.

Thanks
