### ISSUE TITLE
Computer gets stuck when <conda install> some packages, use <pip install> instead 

### ISSUE THREAD

**Issue by asarnats** [hsf-training/analysis-essentials#49]
When installing the following packages with conda, my computer gets stuck (memory overflow?):
pandas, tensorflow, xgboost, hep_ml, wget.

pip did the installation in no-time.

**Comment by jonas-eschle** [comment]
Hi, thanks for posting. Why do you think this has to do with the starterkit? To me it looks rather like a conda or pip issue. Is there maybe a specific part in the starterkit?

**Comment by asarnats** [comment]
The command is written on the following website: https://hsf-training.github.io/analysis-essentials/index.html . As preparation for the Starterkit, I followed the steps on Analysis Essentials. As such I came across this issue.

**Comment by jonas-eschle** [comment]
This should be resolved, closing
